services:
  deezer-app:
    build:
      context: .
    container_name: deezer-mix-refresh
    restart: unless-stopped
    env_file:
      - .env
    environment:
      STATE_FILE_PATH: /app/state.json
    volumes:
      - ./.env:/app/.env:ro
      - ./state.json:/app/state.json
    ports:
      - "127.0.0.1:3457:3457"
